FROM mcr.microsoft.com/dotnet/sdk:8.0 AS development
WORKDIR /app

COPY ["notification-service.csproj", "./"]
RUN dotnet restore "notification-service.csproj"

COPY . .

EXPOSE 8080

ENTRYPOINT ["dotnet", "watch", "run", "--no-launch-profile", "--urls", "http://0.0.0.0:8080"]